sudo: false

language: c

compiler:
  - clang
  - gcc

script:
  - $CC -std=c11 -O2 -c zdis.c
  
notifications:
  irc:
    channels:
      - "irc.choopa.net#cemu-dev"
    on_success: change
    on_failure: always
    skip_join: true
